//
// Generated file, do not edit! Created by nedtool 5.5 from tictoc.msg.
//

#ifndef __TICTOC_M_H
#define __TICTOC_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>tictoc.msg:2</tt> by nedtool.
 * <pre>
 * message Tictoc
 * {
 *     int SeqNo;
 *     int MsgType;
 * }
 * </pre>
 */
class Tictoc : public ::omnetpp::cMessage
{
  protected:
    int SeqNo;
    int MsgType;

  private:
    void copy(const Tictoc& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Tictoc&);

  public:
    Tictoc(const char *name=nullptr, short kind=0);
    Tictoc(const Tictoc& other);
    virtual ~Tictoc();
    Tictoc& operator=(const Tictoc& other);
    virtual Tictoc *dup() const override {return new Tictoc(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSeqNo() const;
    virtual void setSeqNo(int SeqNo);
    virtual int getMsgType() const;
    virtual void setMsgType(int MsgType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Tictoc& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Tictoc& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TICTOC_M_H

